name: Security Audit

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    paths:
      - Cargo.toml
      - Cargo.lock

  pull_request:

jobs:
  security-audit:
    name: Security Audit

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run `cargo audit`
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
